export const GET_ALL_POSTS_START = 'GET_ALL_POSTS_START';
export const  GET_ALL_POSTS_SUCCESS = ' GET_ALL_POSTS_SUCESS';
export const  GET_ALL_POSTS_ERROR = ' GET_ALL_POSTS_ERROR';

export const GET_POST_START = 'GET_POST_START';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_ERROR = 'GET_POST_ERROR';

export const POST_POST_START = 'POST_POST_START';
export const POST_POST_SUCCESS = 'POST_POST_SUCCESS';
export const POST_POST_ERROR = 'POST_POST_ERROR';
